version: '3.4'

services:
  imaginelineswebspa:
    image: ${DOCKER_REGISTRY-}imaginelineswebspa
    build:
      context: .
      dockerfile: ImagineLinesWebSPA/Dockerfile

  booking.api:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Booking.API/Dockerfile

