// <auto-generated />
using System;
using Booking.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Booking.API.Infrastructure.BookingMigrations
{
    [DbContext(typeof(BookingContext))]
    partial class BookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Booking.API.Model.Booking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("bookingDate");

                    b.Property<float>("price");

                    b.Property<int?>("shipid");

                    b.HasKey("id");

                    b.HasIndex("shipid");

                    b.ToTable("booking");
                });

            modelBuilder.Entity("Booking.API.Model.SalesUnit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("country");

                    b.Property<string>("currency");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("salesUnit");
                });

            modelBuilder.Entity("Booking.API.Model.Ship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.Property<int?>("salesUnitid");

                    b.HasKey("id");

                    b.HasIndex("salesUnitid");

                    b.ToTable("ship");
                });

            modelBuilder.Entity("Booking.API.Model.Booking", b =>
                {
                    b.HasOne("Booking.API.Model.Ship", "ship")
                        .WithMany()
                        .HasForeignKey("shipid");
                });

            modelBuilder.Entity("Booking.API.Model.Ship", b =>
                {
                    b.HasOne("Booking.API.Model.SalesUnit", "salesUnit")
                        .WithMany()
                        .HasForeignKey("salesUnitid");
                });
#pragma warning restore 612, 618
        }
    }
}
